eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 8100
spring:
  application:
    name: gateway
zuul:
  routes:
    user-service:
      path: /api/**
      serviceId: user-service
